### ISSUE TITLE
Unused parameters in the Compare/Merge-ObjectGraph functions

### ISSUE THREAD

**Issue by ykuijs** [iRon7/ObjectGraphTools#16]
@RobertDutch requested me to create these issue

A large number of parameters specified in the Compare- and Merge-ObjectGraph functions are not used in the function itself. However, they are used in the subfunction that is created within the main function, but are not explicitly passed into the function.

Best Practice is to use input parameter to insert data into a function. The current method can cause some confusion. I think it would be good to declare and use parameter for inputting this data.

**Comment by iRon7** [comment]
Implemented in a version prior `0.0.10`.
