### ISSUE TITLE
Unit test improvements

### ISSUE THREAD

**Issue by ykuijs** [iRon7/ObjectGraphTools#18]
@RobertDutch requested me to create this issue

The unit tests need some improvements:
- The unit tests for the PSNode class and the Copy function do not exist yet.
- The unit test for the Compare function doesn't hit a large number of lines (approx. 56 lines are not tested).

Could these improvements be implemented?

**Comment by iRon7** [comment]
I have closed this issue as (Pester) unit tests are added regular and will continue to be added on the fly in the future.
