### ISSUE TITLE
Sort verb is a reserved verb

### ISSUE THREAD

**Issue by ykuijs** [iRon7/ObjectGraphTools#19]
@RobertDutch requested me to create this issue

The Sort verb is a reserved verb and should not be used, see [here](https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.4#verb-naming-recommendations).

By using this verb, loading the module results in various warnings. A solution is to use an approved verb and then add an alias for the function. E.g.: Name the function `ConvertTo-SortedObjectGraph` and add this line at the bottom of the file `Set-Alias -Name 'Sort-ObjectGraph' -Value 'ConvertTo-SortedObjectGraph' -Scope Global`

**Comment by iRon7** [comment]
@ykuijs,

Thanks for the issue and the suggestion a workaround.
You might of cause use [`Import-Module -disablenamechecking`](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/import-module#-disablenamechecking) but there no solution for e.g. `using module ..\ObjectGraphTools.psm1` (as in the pester tests).
I will put this in the next release.

Related: https://github.com/PowerShell/PowerShell/issues/3370

**Comment by ykuijs** [comment]
You are absolutely right that it is possible to supress the warnings using the "disablenamechecking" parameter. But having to use parameters to supress warning messages doesn't sound very sensible to me. That is why I prefer a more robust method like the one I suggested 😉

Thanks for implementing that!

**Comment by iRon7** [comment]
Implemented
