### ISSUE TITLE
Compare-ObjectGraph seems to be case sensitive, even when not using the MatchCase parameter

### ISSUE THREAD

**Issue by ykuijs** [iRon7/ObjectGraphTools#20]
@RobertDutch requested me to create this issue

The Compare-ObjectGraph function seems to do a case sensitive compare, even hen you do not specify the MatchCase switch. The unit test fails when you configure the following text in lowercase: https://github.com/iRon7/ObjectGraphTools/blob/339e92fea9cae8622f61d1f7af21785865058e39/Tests/Compare-ObjectGraph.Tests.ps1#L47

This looks like a bug.

**Comment by iRon7** [comment]
Fixed in `0.0.15`
